name: '🐛 Bug Report'
description: 回報專案問題
body:
  - type: markdown
    attributes:
      value: '在提交問題之前，請閱讀並遵循以下說明：'
  - type: markdown
    attributes:
      value: |
        - 確認您的 issue 尚未有人[回報](https://github.com/taipei-doit/codefest.taipei-2026-spring/issues)。
        - 確認該問題在最新版本中尚未修復。
  - type: textarea
    id: description
    attributes:
      label: '描述這個問題'
      description: 清楚且簡潔地描述問題。
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: '重現問題'
      description: |
        提供可重現問題的程式碼片段，若您可以提供一個線上範例在 https://codesandbox.io/ 或是一個 repository 來重現問題那會更好。
        若您的問題無法重現，請將其歸類為**使用問題**。
    validations:
      required: false
  - type: textarea
    id: expected
    attributes:
      label: '預期行為'
      description: 清楚且簡潔地描述您預期應該發生的情況。
    validations:
      required: false
  - type: markdown
    attributes:
      value: Environment
  - type: input
    id: node-version
    attributes:
      label: 'Node.js 版本'
      description: 'node --version'
      placeholder: 'e.g. 18.12.1'
  - type: input
    id: os
    attributes:
      label: 'OS'
      placeholder: 'e.g. iOS 16.0.2, OSX 12.6.0'
  - type: textarea
    id: additional-context
    attributes:
      label: '額外資訊/截圖'
      description: 額外有關問題的其他相關資訊。如果情況允許，請附上截圖以協助說明問題。
      render: bash
    validations:
      required: false
